#!/usr/bin/env bash

i=1
# list-based for loop
for fruit in apple pear banana kiwi; do
    echo "yummy fruit $i: $fruit"
    (( i+=1 ))
done

# range-based for loop (brace expansion)
for i in {1..5}; do
    echo "$i"
done

# doesn't give the range
end=5
for i in {1..$end}; do
   echo "$i"
done

# use C-style for-loop instead of having variable
end=5
for (( i=0; i<end; i++ )); do
    echo "$((i*2))"
done
