#!/usr/bin/env bash

echo "5*3 = $((5*3))"
echo "5-3 = $((5-3))"
echo "5+3 = $((5+3))"
# % modulo operator -> remainder
echo "5%3 = $((5%3))"
# / integer division
echo "5/3 = $((5/3))"

echo "scale=2; 5/3" | bc

PI=3.141592
radius=1
area=$(echo "scale=1; $PI*$radius^2" | bc
)

echo "circle area: $area"
