#!/usr/bin/env bash

# setup
declare -A file_type

mkdir -p assets
touch assets/cool{1..3}.md assets/secret{1..5}.pdf assets/cool_script

mkdir -p assets/cool_dir{1..4}

chmod +x assets/cool_script

# check all files in a directory
# store what type of file it is
# regular, executable, directory

for f in assets/*; do 
    filename="${f#*/}"
    echo "$filename"
    if [[ -d "$f" ]]; then
        file_type["$filename"]="directory"
    elif [[ -x "$f" ]]; then
        file_type["$filename"]="executable"
    else
        file_type["$filename"]="regular file"
    fi

done

for f in "${!file_type[@]}"; do
    echo "$f -> ${file_type[$f]}"
done
